"""
pairwise_potential.py — the N-body / particle potential V(q | ctx).

Irregular-node systems (particles, no grid) break the periodic-domain
assumption behind the FNO spectral layer in OperatorPotential, so the correct
energy structure is a PAIR potential:

    V(q) = sum_{i<j} phi(q_i - q_j | ctx)

Translation-invariant (depends only on differences) and permutation-invariant
(sum over unordered pairs) — the two symmetries any particle energy must
respect. phi is a smooth (Tanh) MLP so the Hamiltonian field dV/dq is C^2.
Context conditions phi by concatenation (the inferred mass distribution, e.g.).

This is the P2-1 building block: it makes the hard-constraint Hamiltonian
applicable to gravitational N-body / collision systems generated by
datasets.gen_nbody.
"""

from __future__ import annotations

from typing import Optional, Tuple

import torch
import torch.nn as nn


def _energy_mlp(dim: int, hidden_dim: int, depth: int) -> nn.Sequential:
    layers: list[nn.Module] = []
    d = dim
    for _ in range(depth):
        layers += [nn.Linear(d, hidden_dim), nn.Tanh()]
        d = hidden_dim
    layers += [nn.Linear(d, 1)]
    return nn.Sequential(*layers)


class PairwisePotential(nn.Module):
    """V(q | ctx) = sum_{i<j} phi(|q_i - q_j| ; ctx), q: (B, N, dim).

    RADIAL pair potential: phi sees only the distance |q_i - q_j|, so the energy
    is translation-, permutation- AND rotation-invariant (the three symmetries
    of a central-force system like gravity / Lennard-Jones). A vector-input phi
    would NOT be permutation-invariant unless it were even — the radial form
    sidesteps that entirely and matches the physics of the N-body generator."""

    def __init__(self, dim: int, hidden_dim: int = 64, depth: int = 2,
                 context_dim: int = 0):
        super().__init__()
        self.dim = int(dim)
        self.context_dim = int(context_dim)
        self.phi = _energy_mlp(1 + context_dim, hidden_dim, depth)

    def forward(self, q: torch.Tensor,
                context: Optional[torch.Tensor] = None) -> torch.Tensor:
        B, N, D = q.shape
        assert D == self.dim, f"q has dim {D}, potential expects {self.dim}"
        diff = q.unsqueeze(2) - q.unsqueeze(1)               # (B, N, N, D)
        i, j = torch.triu_indices(N, N, offset=1)            # upper triangle i < j
        r = diff[:, i, j].norm(dim=-1, keepdim=True)         # (B, M, 1) distances
        if context is not None:
            ctx = context.unsqueeze(1).expand(-1, r.shape[1], -1)
            r = torch.cat([r, ctx], dim=-1)
        e = self.phi(r).squeeze(-1)                          # (B, M)
        return e.sum(dim=1)                                  # (B,)


class NBodyHamiltonianHead(nn.Module):
    """H(q, v | ctx) = T(v) + V_pair(q | ctx) for unit-mass N-body systems.

    q, v are (..., N, dim) positions / velocities (the physics_ops convention).
    T(v) = 0.5 * sum_i |v_i|^2 (unit mass, analytic dT/dv = v). V is the radial
    PairwisePotential. Velocity-Verlet (kick-drift-kick) — identical scheme to
    the other heads, so energy conservation stays architectural.

    This is the P2-1 head: the same hard-constraint route applied to
    irregular-node (particle) systems, where the pair potential replaces the
    FNO spectral layer.
    """

    def __init__(self, dim: int, hidden_dim: int = 64, depth: int = 2,
                 context_dim: int = 0):
        super().__init__()
        self.dim = int(dim)
        self.context_dim = int(context_dim)
        self.V = PairwisePotential(dim, hidden_dim, depth, context_dim)

    def energy(self, q: torch.Tensor, v: torch.Tensor,
               context: Optional[torch.Tensor] = None) -> torch.Tensor:
        """T(v) + V_pair(q | ctx); (..., N, dim) -> (...,). Leading dims are
        flattened (e.g. (k+1, B, N, dim) rollout tensors) and a (B, d) context
        is broadcast along them first (same contract as
        OperatorHamiltonianHead.energy)."""
        lead = q.shape[:-2]
        qf = q.reshape(-1, *q.shape[-2:])
        vf = v.reshape(-1, *v.shape[-2:])
        t = 0.5 * vf.pow(2).sum(dim=(-1, -2))                # (B',)
        if context is not None:
            # rollout flattening is (lead..., B, N, dim) with B innermost, so
            # tiling the (B, d) context lead-major realigns it
            cf = context.repeat(qf.shape[0] // context.shape[0], 1)
        else:
            cf = None
        e = t + self.V(qf, cf)                               # (B',)
        return e.reshape(lead)

    def dV_dq(self, q: torch.Tensor,
              context: Optional[torch.Tensor] = None) -> torch.Tensor:
        if not q.requires_grad:
            q = q.requires_grad_(True)
        (g,) = torch.autograd.grad(self.V(q, context).sum(), q,
                                   create_graph=self.training)
        return g

    def step(self, q: torch.Tensor, v: torch.Tensor, dt: float,
             context: Optional[torch.Tensor] = None
             ) -> Tuple[torch.Tensor, torch.Tensor]:
        dt = float(dt)
        a = -self.dV_dq(q, context)                          # force = -dV/dq
        v_half = v + 0.5 * dt * a
        q_next = q + dt * v_half                             # dT/dv = v (unit mass)
        v_next = v_half + 0.5 * dt * (-self.dV_dq(q_next, context))
        return q_next, v_next

    def rollout(self, q0: torch.Tensor, v0: torch.Tensor, steps: int, dt: float,
                context: Optional[torch.Tensor] = None
                ) -> Tuple[torch.Tensor, torch.Tensor]:
        qs, vs = [q0], [v0]
        q, v = q0, v0
        for _ in range(int(steps)):
            q, v = self.step(q, v, dt, context)
            qs.append(q)
            vs.append(v)
        return torch.stack(qs), torch.stack(vs)
